version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    # Intentionally a very high limit:
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "github-actions"
